### ISSUE TITLE
[FEATURE] Feedback form

### ISSUE THREAD

**Issue by saglaniharsh** [ashawe/CTF-Website-Template-2020#5]
A feedback form containing questions regarding
- Questions
- Ease of access
- Interface
- Enjoyment
- Would play again?
- Would recommend playing?
- Organizers
- Maintainers
- Overall

etc.

**Comment by jcombs0929** [comment]
May I help with this?

**Comment by saglaniharsh** [comment]
Sure. Go ahead @jcombs0929. I'll assign this to you.

Make sure you create a new page.

**Comment by jcombs0929** [comment]
@ashawe Where/how do you want this page linked?

**Comment by saglaniharsh** [comment]
@jcombs0929 So basically, this page comes when the event is over ( i.e. the timer runs out ).
But since there is no backend functionality, you don't need to link this page to anything. 
Just create a feedback.html page
