### ISSUE TITLE
Preloader loads everytime

### ISSUE THREAD

**Issue by saglaniharsh** [ashawe/CTF-Website-Template-2020#8]
**Current Behavior:** The preloader i.e. the screen which resembles the boot loading process when you visit the home page runs every time you visit the page.

**Expected Behavior:** It should only run once i.e. when the user visits the website for the first time!

**Suggestions on how to solve this issue:** I think a way to solve this issue would be to set a cookie once the preloader is shown. So next time if someone visits the webpage, we can check if the cookie is set and not show it again.

**Comment by kud04rk** [comment]
@ashawe I set the cookie and checked the cookie when the user visits the website again.
created pull request #9 please check and merge #9
